# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-target-blank

# Conversion
markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM

# Serving
baseurl: /
future: false

# Outputting
permalink: /:year/:month/:day/:title
paginate:  15
timezone:  UTC
quiet:     false

# Theme
url:         https://rpanachi.com
author:      Rodrigo Panachi
description: Rodrigo Panachi's tech blog
bio:         A Software Engineer that like to code and learn new things. Follow my thoughts on <a href="https://twitter.com/rpanachi">Twitter</a>, fork my code on <a href="https://github.com/rpanachi">Github</a> and hire me on <a href="https://linkedin.com/in/rpanachi">Linkedin</a>.

# Custom Configs
disqus_id: rpanachi
google_analytics: 'G-HHZCBHXG3L'
links:
  github:   https://github.com/rpanachi
  twitter:  https://twitter.com/rpanachi
  feed:     https://feeds.feedburner.com/rpanachi
  linkedin: https://linkedin.com/in/rpanachi
twitter:
  username: rpanachi
