# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll-archives

# Conversion
markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM

# Serving
baseurl: /
future: false

# Outputting
permalink: /:title
paginate:  15
timezone:  UTC
quiet:     false

# Theme
url:         https://rpanachi.com
author:      Rodrigo Panachi
description: Rodrigo Panachi's tech blog
bio:         A Software Engineer that like to code and learn new things. Subscribe to my <a href="https://feeds.feedburner.com/rpanachi" target="_blank">RSS feed</a> to stay tuned, check my code on <a href="https://github.com/rpanachi">Github</a> and hire me on <a href="https://linkedin.com/in/rpanachi">Linkedin</a>.

# Custom Configs
disqus_id: rpanachi
google_analytics: 'G-HHZCBHXG3L'
links:
  github: https://github.com/rpanachi
  feed: https://feeds.feedburner.com/rpanachi
  linkedin: https://linkedin.com/in/rpanachi
  printables: https://www.printables.com/@rpanachi
twitter:
  username: rpanachi

jekyll-archives:
  enabled: [categories]
  layout: archive
  permalinks:
    category: '/category/:name/'
