name: Scheduled Publish

on:
  schedule:
    - cron: '30 13 * * 1'  # Run at 10:30am (1:30pm UTC) every Monday

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages Publish action
        run: |
          curl --fail --request POST \
        --url https://api.github.com/repos/rpanachi/rpanachi.github.io/actions/workflows/jekyll.yml/dispatches \
        --header "Authorization: token $TOKEN" \
        -d '{"ref":"master"}'
        env:
          TOKEN: ${{ secrets.PUBLISH_TOKEN }} 
